In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [8]:
#가설(식) 세우기
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [10]:
hypothesis = x_train * W + b
print(hypothesis)
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)


tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
tensor(18.6667, grad_fn=<MeanBackward0>)


In [11]:
#경사 하강법 구현
optimizer = optim.SGD([W, b], lr=0.01)
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()


In [13]:
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.353, b: 0.151 Cost: 14.770963
Epoch  100/1999 W: 1.746, b: 0.577 Cost: 0.047939
Epoch  200/1999 W: 1.801, b: 0.453 Cost: 0.029624
Epoch  300/1999 W: 1.843, b: 0.356 Cost: 0.018306
Epoch  400/1999 W: 1.877, b: 0.280 Cost: 0.011312
Epoch  500/1999 W: 1.903, b: 0.220 Cost: 0.006990
Epoch  600/1999 W: 1.924, b: 0.173 Cost: 0.004319
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002669
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001649
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001019
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000630
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000389
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000240
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008